[2025-04-23T15:48:59.808+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T15:48:59.819+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_data_etl_dbt.dbt_test manual__2025-04-23T15:16:33.263567+00:00 [queued]>
[2025-04-23T15:48:59.825+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_data_etl_dbt.dbt_test manual__2025-04-23T15:16:33.263567+00:00 [queued]>
[2025-04-23T15:48:59.825+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 3
[2025-04-23T15:48:59.834+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_test> on 2025-04-23 15:16:33.263567+00:00
[2025-04-23T15:48:59.842+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=30873) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-23T15:48:59.843+0000] {standard_task_runner.py:72} INFO - Started process 30876 to run task
[2025-04-23T15:48:59.842+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_data_etl_dbt', 'dbt_test', 'manual__2025-04-23T15:16:33.263567+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/Stock_built_ELT.py', '--cfg-path', '/tmp/tmp237b70ry']
[2025-04-23T15:48:59.845+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask dbt_test
[2025-04-23T15:48:59.879+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_data_etl_dbt.dbt_test manual__2025-04-23T15:16:33.263567+00:00 [running]> on host 712e28762a67
[2025-04-23T15:48:59.943+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_data_etl_dbt' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T15:16:33.263567+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T15:16:33.263567+00:00'
[2025-04-23T15:48:59.944+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-23T15:48:59.947+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-23T15:48:59.948+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2025-04-23T15:48:59.955+0000] {subprocess.py:86} INFO - Output:
[2025-04-23T15:49:02.574+0000] {subprocess.py:93} INFO - [0m15:49:02  Running with dbt=1.7.19
[2025-04-23T15:49:03.670+0000] {subprocess.py:93} INFO - [0m15:49:03  Registered adapter: snowflake=1.7.1
[2025-04-23T15:49:03.743+0000] {subprocess.py:93} INFO - [0m15:49:03  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-04-23T15:49:03.743+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-04-23T15:49:03.744+0000] {subprocess.py:93} INFO - - models.stock_data_transform_dbt.marts
[2025-04-23T15:49:03.762+0000] {subprocess.py:93} INFO - [0m15:49:03  Found 4 models, 1 snapshot, 1 source, 0 exposures, 0 metrics, 430 macros, 0 groups, 0 semantic models
[2025-04-23T15:49:03.765+0000] {subprocess.py:93} INFO - [0m15:49:03
[2025-04-23T15:49:03.765+0000] {subprocess.py:93} INFO - [0m15:49:03  Nothing to do. Try checking your model configs and model specification args
[2025-04-23T15:49:04.519+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-23T15:49:04.577+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-23T15:49:04.578+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_data_etl_dbt, task_id=dbt_test, run_id=manual__2025-04-23T15:16:33.263567+00:00, execution_date=20250423T151633, start_date=20250423T154859, end_date=20250423T154904
[2025-04-23T15:49:04.625+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T15:49:04.654+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
