[2025-04-12T01:21:35.403+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-12T01:21:35.437+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Medium_to_Pinecone.create_pinecone_index manual__2025-04-12T01:06:01.088950+00:00 [queued]>
[2025-04-12T01:21:35.452+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Medium_to_Pinecone.create_pinecone_index manual__2025-04-12T01:06:01.088950+00:00 [queued]>
[2025-04-12T01:21:35.454+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-04-12T01:21:35.481+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): create_pinecone_index> on 2025-04-12 01:06:01.088950+00:00
[2025-04-12T01:21:35.565+0000] {standard_task_runner.py:72} INFO - Started process 1973 to run task
[2025-04-12T01:21:35.595+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Medium_to_Pinecone', 'create_pinecone_index', 'manual__2025-04-12T01:06:01.088950+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/build_pinecone_search.py', '--cfg-path', '/tmp/tmpjlnww5p7']
[2025-04-12T01:21:35.611+0000] {standard_task_runner.py:105} INFO - Job 248: Subtask create_pinecone_index
[2025-04-12T01:21:35.746+0000] {task_command.py:467} INFO - Running <TaskInstance: Medium_to_Pinecone.create_pinecone_index manual__2025-04-12T01:06:01.088950+00:00 [running]> on host da473742a4a2
[2025-04-12T01:21:35.898+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Medium_to_Pinecone' AIRFLOW_CTX_TASK_ID='create_pinecone_index' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T01:06:01.088950+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-12T01:06:01.088950+00:00'
[2025-04-12T01:21:35.902+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-12T01:21:36.291+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/build_pinecone_search.py", line 106, in create_pinecone_index
    existing_indexes = [index_info["name"] for index_info in pc.list_indexes()]
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/control/pinecone.py", line 235, in list_indexes
    response = self.index_api.list_indexes()
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/endpoint.py", line 102, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/core/openapi/db_control/api/manage_indexes_api.py", line 708, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/endpoint.py", line 134, in call_with_http_info
    return self.api_client.call_api(
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/api_client.py", line 300, in call_api
    return self.__call_api(
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/api_client.py", line 178, in __call_api
    raise e
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/api_client.py", line 166, in __call_api
    response_data = self.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/api_client.py", line 354, in request
    return self.rest_client.GET(
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/rest_utils.py", line 75, in GET
    return self.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/rest_urllib3.py", line 260, in request
    return raise_exceptions_or_return(r)
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/rest_utils.py", line 38, in raise_exceptions_or_return
    raise UnauthorizedException(http_resp=r)
pinecone.openapi_support.exceptions.UnauthorizedException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'x-pinecone-api-version': '2025-01', 'x-cloud-trace-context': 'e9a61a321b9e89d01d697951c2e36baa', 'date': 'Sat, 12 Apr 2025 01:21:36 GMT', 'content-type': 'text/html', 'server': 'Google Frontend', 'Content-Length': '15', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'})
HTTP response body: Invalid API Key

[2025-04-12T01:21:36.325+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Medium_to_Pinecone, task_id=create_pinecone_index, run_id=manual__2025-04-12T01:06:01.088950+00:00, execution_date=20250412T010601, start_date=20250412T012135, end_date=20250412T012136
[2025-04-12T01:21:36.340+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-12T01:21:36.344+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 248 for task create_pinecone_index ((401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'x-pinecone-api-version': '2025-01', 'x-cloud-trace-context': 'e9a61a321b9e89d01d697951c2e36baa', 'date': 'Sat, 12 Apr 2025 01:21:36 GMT', 'content-type': 'text/html', 'server': 'Google Frontend', 'Content-Length': '15', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'})
HTTP response body: Invalid API Key
; 1973)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/build_pinecone_search.py", line 106, in create_pinecone_index
    existing_indexes = [index_info["name"] for index_info in pc.list_indexes()]
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/control/pinecone.py", line 235, in list_indexes
    response = self.index_api.list_indexes()
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/endpoint.py", line 102, in __call__
    return self.callable(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/core/openapi/db_control/api/manage_indexes_api.py", line 708, in __list_indexes
    return self.call_with_http_info(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/endpoint.py", line 134, in call_with_http_info
    return self.api_client.call_api(
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/api_client.py", line 300, in call_api
    return self.__call_api(
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/api_client.py", line 178, in __call_api
    raise e
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/api_client.py", line 166, in __call_api
    response_data = self.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/api_client.py", line 354, in request
    return self.rest_client.GET(
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/rest_utils.py", line 75, in GET
    return self.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/rest_urllib3.py", line 260, in request
    return raise_exceptions_or_return(r)
  File "/home/airflow/.local/lib/python3.10/site-packages/pinecone/openapi_support/rest_utils.py", line 38, in raise_exceptions_or_return
    raise UnauthorizedException(http_resp=r)
pinecone.openapi_support.exceptions.UnauthorizedException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'x-pinecone-api-version': '2025-01', 'x-cloud-trace-context': 'e9a61a321b9e89d01d697951c2e36baa', 'date': 'Sat, 12 Apr 2025 01:21:36 GMT', 'content-type': 'text/html', 'server': 'Google Frontend', 'Content-Length': '15', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'})
HTTP response body: Invalid API Key

[2025-04-12T01:21:36.390+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-12T01:21:36.415+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
